# Generated by Django 4.2.7 on 2025-11-25 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChatRoom",
            new_name="Room",
        ),
    ]
