# Generated by Django 4.2.7 on 2025-11-27 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_rename_chatroom_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
    ]
